import type { LocalizedText, Payslip, PayslipLineRecord, PayrollRun, RunJournalLine } from "@/lib/payroll/types";

// The accounting entries of a payroll run (study 8.4 / 12.3, spec R-6 / R-9 / R-10): pure builders.
//   posting  : Dr salary / overtime / employer-contribution expense · Cr statutory & loan & penalty payables · Cr net salaries payable
//   payment  : Dr net salaries payable · Cr bank / cash
//   reversal : the posting entry with debit and credit swapped
// One entry per cost centre, each balanced on its own (decision 4).

export const NET_PAYABLE_ACCOUNT = "2250";
export const BANK_ACCOUNT = "1120";
export const CASH_ACCOUNT = "1110";
const DEFAULT_EXPENSE = "5110";
const NO_COST_CENTER = "—";

export type AccountNames = Record<string, LocalizedText>;

type Draft = { accountCode: string; debit: number; credit: number; costCenterId: string | null };

function toLines(
  drafts: Draft[],
  run: Pick<PayrollRun, "id" | "runNo" | "periodKey">,
  names: AccountNames,
  kind: RunJournalLine["kind"],
  journalRef: string,
  isReversal = false
): RunJournalLine[] {
  const merged = new Map<string, Draft>();
  for (const d of drafts) {
    const key = `${d.costCenterId ?? NO_COST_CENTER}|${d.accountCode}`;
    const existing = merged.get(key);
    if (existing) {
      existing.debit += d.debit;
      existing.credit += d.credit;
    } else merged.set(key, { ...d });
  }
  return [...merged.values()]
    // net each account inside a cost centre so an account never shows on both sides
    .map((d) => ({ ...d, debit: Math.max(0, d.debit - d.credit), credit: Math.max(0, d.credit - d.debit) }))
    .filter((d) => d.debit !== 0 || d.credit !== 0)
    .sort((a, b) => (a.costCenterId ?? "").localeCompare(b.costCenterId ?? "") || Number(b.debit > 0) - Number(a.debit > 0) || a.accountCode.localeCompare(b.accountCode))
    .map((d, i) => ({
      id: `${run.id}-${kind[0].toLowerCase()}${i + 1}`,
      runId: run.id,
      kind,
      journalRef,
      accountCode: d.accountCode,
      accountName: names[d.accountCode] ?? { ar: d.accountCode, en: d.accountCode },
      debit: d.debit,
      credit: d.credit,
      costCenterId: d.costCenterId,
      projectId: null,
      baseType: "PAYRUN",
      baseEntry: run.id,
      baseRef: run.runNo,
      fiscalPeriodId: `FP-${run.periodKey}`,
      isAutoGenerated: true,
      isReversal,
    }));
}

export function buildPostingJournal(args: {
  run: Pick<PayrollRun, "id" | "runNo" | "periodKey">;
  payslips: Payslip[];
  lines: PayslipLineRecord[];
  names: AccountNames;
  journalRef: string;
}): RunJournalLine[] {
  const costCenterOf = new Map(args.payslips.map((p) => [p.id, p.costCenterId]));
  const drafts: Draft[] = [];
  for (const line of args.lines) {
    if (!costCenterOf.has(line.payslipId) || line.componentType === "Informational" || line.amount === 0) continue;
    const costCenterId = costCenterOf.get(line.payslipId) ?? null;
    if (line.componentType === "Earning") {
      drafts.push({ accountCode: line.expenseAccountCode ?? DEFAULT_EXPENSE, debit: line.amount, credit: 0, costCenterId });
    } else if (line.componentType === "EmployerContribution") {
      drafts.push({ accountCode: line.expenseAccountCode ?? DEFAULT_EXPENSE, debit: line.amount, credit: 0, costCenterId });
      if (line.payableAccountCode) drafts.push({ accountCode: line.payableAccountCode, debit: 0, credit: line.amount, costCenterId });
    } else {
      // deduction: attendance deductions reduce the salary expense, everything else settles a payable
      drafts.push({ accountCode: line.payableAccountCode ?? line.expenseAccountCode ?? DEFAULT_EXPENSE, debit: 0, credit: line.amount, costCenterId });
    }
  }
  for (const p of args.payslips) {
    if (p.netPay !== 0) drafts.push({ accountCode: NET_PAYABLE_ACCOUNT, debit: 0, credit: p.netPay, costCenterId: p.costCenterId });
  }
  return toLines(drafts, args.run, args.names, "Posting", args.journalRef);
}

export function buildPaymentJournal(args: {
  run: Pick<PayrollRun, "id" | "runNo" | "periodKey">;
  payslips: Payslip[];
  names: AccountNames;
  journalRef: string;
}): RunJournalLine[] {
  const drafts: Draft[] = [];
  for (const p of args.payslips) {
    if (p.netPay <= 0) continue;
    drafts.push({ accountCode: NET_PAYABLE_ACCOUNT, debit: p.netPay, credit: 0, costCenterId: p.costCenterId });
    drafts.push({ accountCode: p.paymentMethod === "Cash" ? CASH_ACCOUNT : BANK_ACCOUNT, debit: 0, credit: p.netPay, costCenterId: p.costCenterId });
  }
  return toLines(drafts, args.run, args.names, "Payment", args.journalRef);
}

export function buildReversalJournal(posting: RunJournalLine[], journalRef: string): RunJournalLine[] {
  return posting.map((l, i) => ({
    ...l,
    id: `${l.runId}-r${i + 1}`,
    kind: "Reversal" as const,
    journalRef,
    debit: l.credit,
    credit: l.debit,
    isReversal: true,
  }));
}

/** Per-cost-centre balance check of a journal. */
export function balanceByCostCenter(lines: RunJournalLine[]) {
  const groups = new Map<string, { costCenterId: string | null; debit: number; credit: number }>();
  for (const l of lines) {
    const key = l.costCenterId ?? NO_COST_CENTER;
    const g = groups.get(key) ?? { costCenterId: l.costCenterId, debit: 0, credit: 0 };
    g.debit += l.debit;
    g.credit += l.credit;
    groups.set(key, g);
  }
  return [...groups.values()].map((g) => ({ ...g, balanced: Math.round((g.debit - g.credit) * 100) === 0 }));
}
